# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'szybka_wtyczka_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SzybkaWtyczkaDialogBase(object):
    def setupUi(self, SzybkaWtyczkaDialogBase):
        SzybkaWtyczkaDialogBase.setObjectName("SzybkaWtyczkaDialogBase")
        SzybkaWtyczkaDialogBase.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(SzybkaWtyczkaDialogBase)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")

        self.retranslateUi(SzybkaWtyczkaDialogBase)
        self.button_box.accepted.connect(SzybkaWtyczkaDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(SzybkaWtyczkaDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SzybkaWtyczkaDialogBase)

    def retranslateUi(self, SzybkaWtyczkaDialogBase):
        _translate = QtCore.QCoreApplication.translate
        SzybkaWtyczkaDialogBase.setWindowTitle(_translate("SzybkaWtyczkaDialogBase", "Szybka Wtyczka"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SzybkaWtyczkaDialogBase = QtWidgets.QDialog()
    ui = Ui_SzybkaWtyczkaDialogBase()
    ui.setupUi(SzybkaWtyczkaDialogBase)
    SzybkaWtyczkaDialogBase.show()
    sys.exit(app.exec_())
